---
# tasks file for backupninja
- name: Install EPEL repository if needed
  yum_repository:
    name: "epel"
    baseurl: "https://download.fedoraproject.org/pub/epel/$releasever/$basearch/"
    description: "EPEL YUM repo"
    enabled: "yes"
    gpgcheck: "yes"
    gpgkey: "https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7"
  when: ansible_distribution in ["CentOS", "Red Hat Enterprise Linux", "Fedora"]

- name: Install backupninja packages in DEB distributions
  package:
    name:
      - "backupninja"
      - "mailutils"
    state: present
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Install backupninja packages in RPM distributions
  package:
    name:
      - "backupninja"
      - "mailx"
      - "which"
    state: "present"
  when: ansible_distribution in ["CentOS", "Red Hat Enterprise Linux", "Fedora"]

- name: Deploy TAR template
  template:
    src: "tar.j2"
    dest: "/etc/backup.d/10.tar"
    mode: "0600"
    owner: "root"
    group: "root"

- name: Deploy MySQL backup
  template:
    src: "mysql.j2"
    dest: "/etc/backup.d/20.mysql"
    mode: "0600"
    owner: "root"
    group: "root"
  when: ninja_mysql_enabled

- name: Deploy full TAR template
  vars:
    ninja_backupname: "{{ ninja_backupname_def }}"
    ninja_includes: "{{ ninja_backupdir }}"
    ninja_backupdir: "{{ ninja_backupdir_def }}"
  template:
    src: "tar.j2"
    dest: "/etc/backup.d/30.tar"
    mode: "0600"
    owner: "root"
    group: "root"

- name: Deploy cleanup step template in Backupninja
  template:
    src: "extra.j2"
    dest: "/etc/backup.d/40.sh"
    mode: "0600"
    owner: "root"
    group: "root"
