---
- name: Converge
  hosts: all
  become: true
  vars:
    - ninja_backupname: "test"
    - ninja_backupname_def: "full-test"
    - ninja_backupdir: "/tmp/backups"
    - ninja_backupdir_def: "/def_test"
    - ninja_includes: "/var/www"
    - ninja_mysql_username: "bckadmin"
    - ninja_mysql_userpassword: "hola"
    - ninja_mysql_backupdir: "/tmp/backups"
    - ninja_gpg_user: "popeye@sailor.com"

  roles:
    - role: backupninja

  post_tasks:
    - name: Launching backupninja
      command: backupninja -n
      changed_when: false
