---
- name: Prepare
  hosts: all
  become: true
  vars:
    - ninja_mysql_username: "bckadmin"
    - ninja_mysql_userpassword: "hola"

  pre_tasks:
    - name: Install dependencies in Red Hat based instances
      package:
        name:
          - "mariadb-server"
          - "unzip"
          - "which"
          - "MySQL-python"
        state: "present"
      when: ansible_distribution in ["CentOS", "Red Hat Enterprise Linux", "Fedora"]

    - name: Install dependencies in Debian based instances
      package:
        name:
          - "mariadb-server"
          - "unzip"
          - "python-mysqldb"
        state: "present"
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Create some directories to deploy Nextcloud
      file:
        name: "/var/www/"
        state: "directory"
        mode: "0775"
        owner: "root"
        group: "root"

    - name: Create some files
      copy:
        content: "# The princess is in another castle."
        dest: "/var/www/{{ item }}"
        mode: "0775"
        owner: "root"
        group: "root"
      with_items:
        - "index.php"
        - "config.php"
        - "index.html"

    - name: Start MariaDB in both instances
      systemd:
        name: "mariadb"
        state: "started"

    - name: Ensure that MySQL user password works to avoid errors during the tests
      mysql_user:
        name: "{{ ninja_mysql_username }}"
        password: "{{ ninja_mysql_userpassword }}"
        priv: '*.*:ALL'
        check_implicit_admin: "yes"
        login_user: "root"
        login_password: ""
        state: "present"

    - name: Installing dummy GPG files
      become: true
      vars:
        gpg_user: "root"
        gpg_group: "root"
        gpg_private_key: "files/private.gpg"
        gpg_public_key: "files/public.gpg"
        gpg_trust_file: "files/ownertrust.gpg"
      import_role:
        name: ansible-gpg-import
